export const skillsData = [
  {
    id: 1,
    name: "Python",
    level: "Comfortable",
    imagelight: "/skills-images/python.svg",
    imagedark: "/skills-images/python.svg",
  },
  {
    id: 2,
    name: "C++",
    level: "Comfortable",
    imagelight: "/skills-images/cplusplus.svg",
    imagedark: "/skills-images/cplusplus.svg",
  },
  {
    id: 3,
    name: "Pytorch",
    level: "Learning",
    imagelight: "/skills-images/pytorch.svg",
    imagedark: "/skills-images/pytorch.svg",
  },
  {
    id: 4,
    name: "Tensorflow",
    level: "Learning",
    imagelight: "/skills-images/tensorflow.svg",
    imagedark: "/skills-images/tensorflow.svg",
  },
  {
    id: 5,
    name: "Java",
    level: "Comfortable",
    imagelight: "/skills-images/java.svg",
    imagedark: "/skills-images/java.svg",
  },
  {
    id: 6,
    name: "C",
    level: "Learning",
    imagelight: "/skills-images/c.svg",
    imagedark: "/skills-images/c.svg",
  },
  {
    id: 7,
    name: "Typescript",
    level: "Comfortable",
    imagelight: "/skills-images/typescript.svg",
    imagedark: "/skills-images/typescript.svg",
  },
  {
    id: 8,
    name: "Javascript",
    level: "Comfortable",
    imagelight: "/skills-images/javascript.svg",
    imagedark: "/skills-images/javascript.svg",
  },
  {
    id: 9,
    name: "HTML",
    level: "Comfortable",
    imagelight: "/skills-images/html5.svg",
    imagedark: "/skills-images/html5.svg",
  },
  {
    id: 10,
    name: "CSS",
    level: "Comfortable",
    imagelight: "/skills-images/css3.svg",
    imagedark: "/skills-images/css3.svg",
  },
  {
    id: 11,
    name: "Tailwind",
    level: "Comfortable",
    imagelight: "/skills-images/tailwind.svg",
    imagedark: "/skills-images/tailwind.svg",
  },
  {
    id: 12,
    name: "React",
    level: "Comfortable",
    imagelight: "/skills-images/react.svg",
    imagedark: "/skills-images/react.svg",
  },
  {
    id: 13,
    name: "NextJS",
    level: "Comfortable",
    imagelight: "/skills-images/nextjs.svg",
    imagedark: "/skills-images/nextjs-dark.svg",
  },
  {
    id: 14,
    name: "Golang",
    level: "Learning",
    imagelight: "/skills-images/golang.svg",
    imagedark: "/skills-images/golang.svg",
  },
  {
    id: 15,
    name: "Rust",
    level: "Learning",
    imagelight: "/skills-images/rust.svg",
    imagedark: "/skills-images/rust-dark.svg",
  },
  {
    id: 16,
    name: "R",
    level: "Learning",
    imagelight: "/skills-images/rstudio.svg",
    imagedark: "/skills-images/rstudio.svg",
  },
  {
    id: 17,
    name: "ThreeJS",
    level: "Learning",
    imagelight: "/skills-images/threejs.svg",
    imagedark: "/skills-images/threejs-dark.svg",
  },
  {
    id: 18,
    name: "LATEX",
    level: "Comfortable",
    imagelight: "/skills-images/latex.svg",
    imagedark: "/skills-images/latex-dark.svg",
  },
] as const;
